version: '3'

services:
    #################### PROMETHEUS ####################
    prometheus:
        image: prom/prometheus
        restart: unless-stopped
        ports:
            - 9090:9090
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--storage.tsdb.path=/prometheus'
            - '--web.console.libraries=/usr/share/prometheus/console_libraries'
            - '--web.console.templates=/usr/share/prometheus/consoles'
            - '--web.enable-lifecycle'
        volumes:
            - "./prometheus.yml:/etc/prometheus/prometheus.yml"
            - "./rules.yml:/etc/prometheus/rules.yml"
            - "prometheus_storage:/prometheus"
        networks:
            - dev-network
            - default
    #################### NODE-EXPORTER ####################
    node-exporter:
        image: prom/node-exporter
        restart: unless-stopped
        ports:
            - 9100:9100
        networks:
            - default
    #################### ALERT-MANAGER ####################
    alert-manager:
        image: prom/alertmanager
        restart: unless-stopped
        ports:
            - 9093:9093
        command:
            - '--config.file=/config/alertmanager.yml'
            - '--log.level=debug'
            # - '--storage.path=/data'
        volumes:
            - ./alertmanager.yml:/config/alertmanager.yml
            # - "alertmanager_storage:/data"
        networks:
            - default
    #################### GRAFANA ####################
    grafana:
        image: grafana/grafana-enterprise:9.4.7
        container_name: grafana
        restart: unless-stopped
        ports:
            - '3000:3000'
        environment:
            # increases the log level from info to debug
            - GF_LOG_LEVEL=debug
        volumes:
            - 'grafana_storage:/var/lib/grafana'
        networks:
            - default

volumes:
    prometheus_storage: {}
    alertmanager_storage: {}
    grafana_storage: {}

networks:
    default:
    dev-network:
        name: common-containers_dev-network
        external: true