global:
  scrape_interval: 1m
  evaluation_interval: 1m
rule_files:
  - rules.yml
alerting:
  alertmanagers:
   - static_configs:
     - targets:
        - alert-manager:9093
scrape_configs:
 - job_name: prometheus
   static_configs:
    - targets:
       - prometheus:9090
 - job_name: node-exporter
   static_configs:
    - targets:
       - node-exporter:9100
 - job_name: laravel-test
   scrape_interval: 30s
   metrics_path: /Test/laravel-10/public/metrics
   static_configs:
    - targets:
       - apache-dev
